# fos_user:
#     db_driver: orm # other valid values are 'mongodb' and 'couchdb'
#     firewall_name: main
#     user_class: App\Entity\User
#     from_email:
#         address: "pierre.emmanuel.tanguy@gmail.com"
#         sender_name: "pierre.emmanuel.tanguy@gmail.com"
#     service:
#         mailer:                 fos_user.mailer.default
#         email_canonicalizer:    fos_user.util.canonicalizer.default
#         username_canonicalizer: fos_user.util.canonicalizer.default
#         token_generator:        fos_user.util.token_generator.default
#         user_manager:           fos_user.user_manager.default
